import Layout from "../components/Layout";
import Head from "next/head";
import Hero from "../components/Hero";
import Products from "../components/Products";
import { Articles } from "../components/Articles";
import { Inspiration } from "../components/Inspiration";
import Slider from "../components/Slider";
import Reviews from "../components/Review";
import { Overview } from "../components/Overview";

export default function Home() {
  return (
    <>
      <Head>
        <title>Enviable</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        {/* Google fonts  */}
        <link
          href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&family=Inter:wght@400;600;800&family=Poppins:wght@400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Layout>
        <Hero></Hero>
        <Products></Products>
        <Reviews></Reviews>
        <Slider></Slider>
        <Articles></Articles>
        <Inspiration></Inspiration>
        {/* <Overview></Overview> */}
      </Layout>
    </>
  );
}
