import getEnvVar from "./get-env-var";

const HOURS_OF_DATA_TO_UPDATE = 2;
// SECONDS
const MILI_SECONDS_IN_ONE_SECOND = 1000;
const SECONDS_IN_ONE_MINUTE = 60;

// MINUTES
const MILI_SECONDS_IN_ONE_MINUTE =
  SECONDS_IN_ONE_MINUTE * MILI_SECONDS_IN_ONE_SECOND;
const MINUTES_IN_ONE_HOUR = 60;

// HOUR
const MILI_SECONDS_IN_ONE_HOUR =
  MINUTES_IN_ONE_HOUR * MILI_SECONDS_IN_ONE_MINUTE;

// DAY
const HOURS_IN_ONE_DAY = 24;
const MILI_SECONDS_IN_ONE_DAY = HOURS_IN_ONE_DAY * MILI_SECONDS_IN_ONE_HOUR;

export const HOURS_OF_DATA_TO_UPDATE_IN_MILI_SECOND =
  MILI_SECONDS_IN_ONE_HOUR * HOURS_OF_DATA_TO_UPDATE;

export const NOTION_REPOSITORY_DATABASE_ID = getEnvVar(
  "NOTION_REPOSITORY_DATABASE_ID",
  true
);
export const NOTION_SEEDER_SLACK_WEBHOOK_URL = getEnvVar(
  "NOTION_SEEDER_SLACK_WEBHOOK_URL",
  true
);
export const NOTION_SEEDER_DEV_SLACK_WEBHOOK_URL = getEnvVar(
  "NOTION_SEEDER_DEV_SLACK_WEBHOOK_URL",
  true
);
export const NOTION_CATAGORIES_DATABASE_ID = getEnvVar(
  "NOTION_CATAGORIES_DATABASE_ID",
  true
);

export const NOTION_RELATED_CONTENT_DATABASE_ID = getEnvVar(
  "NOTION_RELATED_CONTENT_DATABASE_ID",
  true
);
export const NOTION_PRODUCTS_DATABASE_ID = getEnvVar(
  "NOTION_PRODUCTS_DATABASE_ID",
  true
);

export const STRAPI_ENDPOINT = getEnvVar("STRAPI_ENDPOINT", true);
